/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import static GLOBAL.HelperFunctions.openURL;
import GLOBAL.Settings;
import java.awt.Graphics;

/**
 *
 * @author feine
 */
public class CreditsForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form CreditsForm
     */
    public CreditsForm() {
        initComponents();
    }
    
    /*---- Helper Functions ----*/

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                g.drawImage(new Settings().BACKGROUND_IMAGE_BODY, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jLabel6 = new javax.swing.JLabel();
        lblCreditURL9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCreditURL2 = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                g.drawImage(new Settings().BACKGROUND_IMAGE_HEADER, 0, 0, getWidth(), getHeight(), this);
            }
        };
        lblTitle = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCreditURL3 = new javax.swing.JLabel();
        lblCreditURL4 = new javax.swing.JLabel();
        lblCreditURL5 = new javax.swing.JLabel();
        lblCreditURL6 = new javax.swing.JLabel();
        lblCreditURL7 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblCreditURL10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCreditURL11 = new javax.swing.JLabel();
        lblCreditURL12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblCreditURL13 = new javax.swing.JLabel();
        lblCreditURL14 = new javax.swing.JLabel();
        lblCreditURL15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblCreditURL16 = new javax.swing.JLabel();
        lblCreditURL17 = new javax.swing.JLabel();
        lblCreditURL18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 670));
        setMinimumSize(new java.awt.Dimension(1000, 670));
        setPreferredSize(new java.awt.Dimension(1000, 670));

        pnlMain.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Form and Panel background images");

        lblCreditURL9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblCreditURL9.setForeground(new java.awt.Color(153, 255, 51));
        lblCreditURL9.setText("https://www.wallpaperflare.com/");
        lblCreditURL9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreditURL9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreditURL1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Program, Title, Menu and Button icons");

        lblCreditURL2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblCreditURL2.setForeground(new java.awt.Color(153, 255, 51));
        lblCreditURL2.setText("https://www.flaticon.com/");
        lblCreditURL2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreditURL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreditURL2MouseClicked(evt);
            }
        });

        pnlHeader.setBackground(new java.awt.Color(0, 102, 153));

        lblTitle.setBackground(new java.awt.Color(51, 51, 51));
        lblTitle.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText(" CREDITS");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Helpful + Useful codes and ideas");

        lblCreditURL3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblCreditURL3.setForeground(new java.awt.Color(153, 255, 51));
        lblCreditURL3.setText("https://stackoverflow.com/");
        lblCreditURL3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreditURL3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreditURL3MouseClicked(evt);
            }
        });

        lblCreditURL4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblCreditURL4.setForeground(new java.awt.Color(153, 255, 51));
        lblCreditURL4.setText("https://www.w3schools.com/");
        lblCreditURL4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreditURL4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreditURL4MouseClicked(evt);
            }
        });

        lblCreditURL5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblCreditURL5.setForeground(new java.awt.Color(153, 255, 51));
        lblCreditURL5.setText("https://www.javatpoint.com/");
        lblCreditURL5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreditURL5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreditURL5MouseClicked(evt);
            }
        });

        lblCreditURL6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblCreditURL6.setForeground(new java.awt.Color(153, 255, 51));
        lblCreditURL6.setText("https://beginnersbook.com/");
        lblCreditURL6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreditURL6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreditURL6MouseClicked(evt);
            }
        });

        lblCreditURL7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblCreditURL7.setForeground(new java.awt.Color(153, 255, 51));
        lblCreditURL7.setText("https://www.flaticon.com/authors/freepik");
        lblCreditURL7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreditURL7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreditURL7MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Program and Database Design");

        lblCreditURL10.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblCreditURL10.setForeground(new java.awt.Color(255, 255, 0));
        lblCreditURL10.setText("Mr. Marut Nuchbanpa");
        lblCreditURL10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Programmer");

        lblCreditURL11.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblCreditURL11.setForeground(new java.awt.Color(255, 255, 0));
        lblCreditURL11.setText("Mr. Marut Nuchbanpa");
        lblCreditURL11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCreditURL12.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblCreditURL12.setForeground(new java.awt.Color(255, 255, 0));
        lblCreditURL12.setText("Mr. Pichit Wongwai");
        lblCreditURL12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tester");

        lblCreditURL13.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblCreditURL13.setForeground(new java.awt.Color(255, 255, 0));
        lblCreditURL13.setText("-");
        lblCreditURL13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCreditURL14.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblCreditURL14.setForeground(new java.awt.Color(255, 255, 0));
        lblCreditURL14.setText("-");
        lblCreditURL14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCreditURL15.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblCreditURL15.setForeground(new java.awt.Color(255, 255, 0));
        lblCreditURL15.setText("-");
        lblCreditURL15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Documenter");

        lblCreditURL16.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblCreditURL16.setForeground(new java.awt.Color(255, 255, 0));
        lblCreditURL16.setText("-");
        lblCreditURL16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCreditURL17.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblCreditURL17.setForeground(new java.awt.Color(255, 255, 0));
        lblCreditURL17.setText("-");
        lblCreditURL17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCreditURL18.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblCreditURL18.setForeground(new java.awt.Color(153, 255, 51));
        lblCreditURL18.setText("https://jsonformatter.curiousconcept.com/");
        lblCreditURL18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreditURL18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreditURL18MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Project Team Members");

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Resources");

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCreditURL15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCreditURL14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCreditURL13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCreditURL12, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCreditURL11, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCreditURL10, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCreditURL17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCreditURL16, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCreditURL9, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCreditURL2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCreditURL7, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCreditURL6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCreditURL3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCreditURL4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCreditURL5, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCreditURL18, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCreditURL9))
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCreditURL10)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCreditURL2))
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCreditURL11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCreditURL7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCreditURL12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreditURL3)
                    .addComponent(lblCreditURL13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreditURL4)
                    .addComponent(lblCreditURL14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreditURL5)
                    .addComponent(lblCreditURL15))
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCreditURL6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCreditURL18))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCreditURL16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCreditURL17)))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCreditURL7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreditURL7MouseClicked

        openURL("https://www.flaticon.com/authors/freepik");

    }//GEN-LAST:event_lblCreditURL7MouseClicked

    private void lblCreditURL6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreditURL6MouseClicked

        openURL("https://beginnersbook.com/");

    }//GEN-LAST:event_lblCreditURL6MouseClicked

    private void lblCreditURL5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreditURL5MouseClicked

        openURL("https://www.javatpoint.com/");

    }//GEN-LAST:event_lblCreditURL5MouseClicked

    private void lblCreditURL4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreditURL4MouseClicked

        openURL("https://www.w3schools.com/");

    }//GEN-LAST:event_lblCreditURL4MouseClicked

    private void lblCreditURL3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreditURL3MouseClicked

        openURL("https://stackoverflow.com/");

    }//GEN-LAST:event_lblCreditURL3MouseClicked

    private void lblCreditURL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreditURL2MouseClicked

        String url = "https://www.flaticon.com/";
        openURL(url);

    }//GEN-LAST:event_lblCreditURL2MouseClicked

    private void lblCreditURL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreditURL1MouseClicked

        openURL("https://www.wallpaperflare.com/");

    }//GEN-LAST:event_lblCreditURL1MouseClicked

    private void lblCreditURL18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreditURL18MouseClicked
        
        openURL("https://jsonformatter.curiousconcept.com/");
        
    }//GEN-LAST:event_lblCreditURL18MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCreditURL10;
    private javax.swing.JLabel lblCreditURL11;
    private javax.swing.JLabel lblCreditURL12;
    private javax.swing.JLabel lblCreditURL13;
    private javax.swing.JLabel lblCreditURL14;
    private javax.swing.JLabel lblCreditURL15;
    private javax.swing.JLabel lblCreditURL16;
    private javax.swing.JLabel lblCreditURL17;
    private javax.swing.JLabel lblCreditURL18;
    private javax.swing.JLabel lblCreditURL2;
    private javax.swing.JLabel lblCreditURL3;
    private javax.swing.JLabel lblCreditURL4;
    private javax.swing.JLabel lblCreditURL5;
    private javax.swing.JLabel lblCreditURL6;
    private javax.swing.JLabel lblCreditURL7;
    private javax.swing.JLabel lblCreditURL9;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
