/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import GLOBAL.Settings;
import java.awt.Desktop;
import java.awt.Graphics;
import java.net.URI;

/**
 *
 * @author feine
 */
public class CreditsForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form CreditsForm
     */
    public CreditsForm() {
        initComponents();
    }
    
    /*---- Helper Functions ----*/
    
    private void openURL(String url) {
        
        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(new URI(url));                
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                g.drawImage(new Settings().BACKGROUND_IMAGE_BODY, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jLabel2 = new javax.swing.JLabel();
        lblCreditURL1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCreditURL2 = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                g.drawImage(new Settings().BACKGROUND_IMAGE_HEADER, 0, 0, getWidth(), getHeight(), this);
            }
        };
        lblTitle = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCreditURL3 = new javax.swing.JLabel();
        lblCreditURL4 = new javax.swing.JLabel();
        lblCreditURL5 = new javax.swing.JLabel();
        lblCreditURL6 = new javax.swing.JLabel();
        lblCreditURL7 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 520));
        setMinimumSize(new java.awt.Dimension(600, 520));
        setPreferredSize(new java.awt.Dimension(600, 520));

        pnlMain.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Form and Panel background images");

        lblCreditURL1.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        lblCreditURL1.setForeground(new java.awt.Color(153, 255, 51));
        lblCreditURL1.setText("https://www.wallpaperflare.com/");
        lblCreditURL1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreditURL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreditURL1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Program, Title, Menu and Button icons");

        lblCreditURL2.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        lblCreditURL2.setForeground(new java.awt.Color(153, 255, 51));
        lblCreditURL2.setText("https://www.flaticon.com/");
        lblCreditURL2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreditURL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreditURL2MouseClicked(evt);
            }
        });

        pnlHeader.setBackground(new java.awt.Color(0, 102, 153));

        lblTitle.setBackground(new java.awt.Color(51, 51, 51));
        lblTitle.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("CREDITS");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Helpful + Useful codes and ideas");

        lblCreditURL3.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        lblCreditURL3.setForeground(new java.awt.Color(153, 255, 51));
        lblCreditURL3.setText("https://stackoverflow.com/");
        lblCreditURL3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreditURL3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreditURL3MouseClicked(evt);
            }
        });

        lblCreditURL4.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        lblCreditURL4.setForeground(new java.awt.Color(153, 255, 51));
        lblCreditURL4.setText("https://www.w3schools.com/");
        lblCreditURL4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreditURL4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreditURL4MouseClicked(evt);
            }
        });

        lblCreditURL5.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        lblCreditURL5.setForeground(new java.awt.Color(153, 255, 51));
        lblCreditURL5.setText("https://www.javatpoint.com/");
        lblCreditURL5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreditURL5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreditURL5MouseClicked(evt);
            }
        });

        lblCreditURL6.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        lblCreditURL6.setForeground(new java.awt.Color(153, 255, 51));
        lblCreditURL6.setText("https://beginnersbook.com/");
        lblCreditURL6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreditURL6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreditURL6MouseClicked(evt);
            }
        });

        lblCreditURL7.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        lblCreditURL7.setForeground(new java.awt.Color(153, 255, 51));
        lblCreditURL7.setText("https://www.flaticon.com/authors/freepik");
        lblCreditURL7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreditURL7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreditURL7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCreditURL6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreditURL5, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreditURL4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreditURL3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreditURL7, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreditURL2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlMainLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblCreditURL1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMainLayout.createSequentialGroup()
                            .addGap(152, 152, 152)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCreditURL1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCreditURL2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCreditURL7)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCreditURL3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCreditURL4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCreditURL5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCreditURL6)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCreditURL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreditURL1MouseClicked
        
        String url = "https://www.wallpaperflare.com/";
        openURL(url);
        
    }//GEN-LAST:event_lblCreditURL1MouseClicked

    private void lblCreditURL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreditURL2MouseClicked
        
        String url = "https://www.flaticon.com/";
        openURL(url);
        
    }//GEN-LAST:event_lblCreditURL2MouseClicked

    private void lblCreditURL3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreditURL3MouseClicked
        
        String url = "https://stackoverflow.com/";
        openURL(url);
        
    }//GEN-LAST:event_lblCreditURL3MouseClicked

    private void lblCreditURL4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreditURL4MouseClicked
        
        String url = "https://www.w3schools.com/";
        openURL(url);
        
    }//GEN-LAST:event_lblCreditURL4MouseClicked

    private void lblCreditURL5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreditURL5MouseClicked
        
        String url = "https://www.javatpoint.com/";
        openURL(url);
        
    }//GEN-LAST:event_lblCreditURL5MouseClicked

    private void lblCreditURL6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreditURL6MouseClicked
        
        String url = "https://beginnersbook.com/";
        openURL(url);
        
    }//GEN-LAST:event_lblCreditURL6MouseClicked

    private void lblCreditURL7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreditURL7MouseClicked
                
        String url = "https://www.flaticon.com/authors/freepik";
        openURL(url);
        
    }//GEN-LAST:event_lblCreditURL7MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCreditURL1;
    private javax.swing.JLabel lblCreditURL2;
    private javax.swing.JLabel lblCreditURL3;
    private javax.swing.JLabel lblCreditURL4;
    private javax.swing.JLabel lblCreditURL5;
    private javax.swing.JLabel lblCreditURL6;
    private javax.swing.JLabel lblCreditURL7;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
