/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import DBCLS.*;
import static GLOBAL.EncDec.*;
import static GLOBAL.HelperFunctions.*;
import static GLOBAL.Settings.*;
import static GLOBAL.Varibles.*;
import javax.swing.JOptionPane;
import javax.swing.plaf.FontUIResource;

/**
 *
 * @author feine
 */
public class LoginForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        setUIFont(new FontUIResource(MAIN_FONT));
        
        this.setName("LOGIN_FORM");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tbxUser = new javax.swing.JTextField();
        tbxPass = new javax.swing.JPasswordField();
        btnExit = new javax.swing.JButton();
        btnLogIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblLogInHint = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setFrameIcon(null);
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        tbxUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbxUser.setText("demo");
        tbxUser.setMaximumSize(new java.awt.Dimension(1000, 25));
        tbxUser.setMinimumSize(new java.awt.Dimension(100, 25));
        tbxUser.setPreferredSize(new java.awt.Dimension(100, 25));
        tbxUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbxUserFocusGained(evt);
            }
        });

        tbxPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbxPass.setText("demo");
        tbxPass.setMaximumSize(new java.awt.Dimension(1000, 25));
        tbxPass.setMinimumSize(new java.awt.Dimension(100, 25));
        tbxPass.setPreferredSize(new java.awt.Dimension(100, 25));
        tbxPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbxPassFocusGained(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 51, 51));
        btnExit.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        btnExit.setForeground(new java.awt.Color(51, 51, 51));
        btnExit.setText("EXIT");
        btnExit.setMaximumSize(new java.awt.Dimension(55, 32));
        btnExit.setMinimumSize(new java.awt.Dimension(55, 32));
        btnExit.setPreferredSize(new java.awt.Dimension(55, 32));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnLogIn.setBackground(new java.awt.Color(153, 255, 0));
        btnLogIn.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        btnLogIn.setForeground(new java.awt.Color(51, 51, 51));
        btnLogIn.setText("LOGIN");
        btnLogIn.setMaximumSize(new java.awt.Dimension(71, 32));
        btnLogIn.setMinimumSize(new java.awt.Dimension(71, 32));
        btnLogIn.setName("LogIn"); // NOI18N
        btnLogIn.setPreferredSize(new java.awt.Dimension(71, 32));
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        lblLogInHint.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        lblLogInHint.setForeground(new java.awt.Color(255, 255, 255));
        lblLogInHint.setText("* user: demo / pass: demo");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 2, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Username ");
        jLabel2.setPreferredSize(new java.awt.Dimension(45, 20));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 2, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Password ");
        jLabel4.setPreferredSize(new java.awt.Dimension(45, 20));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/secure64.png"))); // NOI18N

        lblTitle.setBackground(new java.awt.Color(51, 51, 51));
        lblTitle.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(153, 255, 0));
        lblTitle.setText("SYSTEM LOGIN");
        lblTitle.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLogInHint)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tbxUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tbxPass, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(135, 135, 135))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbxUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbxPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(lblLogInHint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(50, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed

        boolean isValid = false;

        String username = tbxUser.getText();
        String password = tbxPass.getText();
        String encPassword = encrypt(password, SECRET_KEY);

        User user = User.LogIn(username, encPassword);
        
        if (user != null) {
            CURRENT_USER = user.toUserInfo();
        }        
        
        Log.LogInfo li = new Log.LogInfo();
        li.id = 0;
        li.log_date = getCurrentDateTimeFormatted();
        li.user = CURRENT_USER.username;
        li.category = "SYSTEM LOG";
        li.event = "LOGIN";    

        if(user != null){                    
            li.details = "User '"+CURRENT_USER.username+"' (User Level: "+getUserLevel(CURRENT_USER.level)+") \n"
                    + "LOGIN\n"
                    + " User[\n"
                    + "  ID: "+CURRENT_USER.id+",\n"
                    + "  Username: "+CURRENT_USER.username+",\n"
                    + "  Password: <***SECRET***>,\n"
                    + "  Email: "+CURRENT_USER.email+",\n"
                    + "  Phone: "+CURRENT_USER.phone+",\n"
                    + "  UserLevel: "+getUserLevel(CURRENT_USER.level)+",\n"
                    + "  Result: SUCCESS\n"
                    + " ]";
            Log.addLog(li);
            this.dispose();
        }else{
            li.details = "User '"+CURRENT_USER.username+"' (User Level: "+getUserLevel(CURRENT_USER.level)+") \n"
                    + "LOGIN\n"
                    + " User[\n"
                    + "  Username: "+username+",\n"
                    + "  Password: <***SECRET***>,\n"
                    + "  Result: FAILED\n"
                    + " ]";
            Log.addLog(li);
            JOptionPane.showMessageDialog(this, "Invalid username and/or password!", "Error", JOptionPane.ERROR_MESSAGE);
            tbxUser.setText("");
            tbxPass.setText("");
            tbxUser.requestFocus();
        }

    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed

        System.exit(0);

    }//GEN-LAST:event_btnExitActionPerformed

    private void tbxPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbxPassFocusGained
        tbxPass.selectAll();
    }//GEN-LAST:event_tbxPassFocusGained

    private void tbxUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbxUserFocusGained
        tbxUser.selectAll();
    }//GEN-LAST:event_tbxUserFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lblLogInHint;
    private javax.swing.JLabel lblTitle;
    public javax.swing.JPasswordField tbxPass;
    public javax.swing.JTextField tbxUser;
    // End of variables declaration//GEN-END:variables
}
