/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import DBCLS.*;
import static GLOBAL.EncDec.*;
import static GLOBAL.HelperFunctions.*;
import GLOBAL.Settings;
import static GLOBAL.Settings.*;
import static GLOBAL.Validator.InputValidation.*;
import GLOBAL.Validator.InputValidation.ValidationResult;
import GLOBAL.Varibles;
import static GLOBAL.Varibles.CURRENT_USER;
import java.awt.Component;
import java.awt.Graphics;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.FontUIResource;


/**
 *
 * @author feine
 */
public class NewUserForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewUser
     */
    public NewUserForm() {
        initComponents();        
        setUIFont(new FontUIResource(MAIN_FONT));
        getContentPane().setBackground(BG_DARK);
        
    }
    
    /*==== Required Code Structure ====*/
    public void callFunction(String functionName) {
        switch(functionName) {
            case "initForm" -> initForm();
        }
    }
    
    enum frameState {
        INIT, POST_EDIT
    }
    
    private void initForm() {
        setFrameState(frameState.INIT);
    }
    
    private void setFrameState(frameState framState) {
        switch(framState) {
            case INIT -> {
                for (Component comp : pnlMainInfo.getComponents()) {
                    if (comp instanceof JTextField) {
                        ((JTextField) comp).setText("");
                    }
                }
                cmbUserLevel.setSelectedIndex(0);
            }
                
            case POST_EDIT -> {
                setFrameState(frameState.INIT);
                
                callUpdateUserData();
            }
        }
    }
    
    
    
    /*==== Helper Functions ====*/
    
    private ValidationResult validateUser(User.UserInfo ui) {
        
        ValidationResult vr;
        
        vr = validateUsername(ui.username);        
        if (!vr.result) {
            tbxUsername.requestFocus();
            return vr;
        }
        
        vr = validatePassword(ui.password);        
        if (!vr.result) {
            tbxPassword.setText("");
            tbxComfirmPassword.setText("");
            tbxPassword.requestFocus();
            return vr;
        }
        
        vr = validateEmail(ui.email);        
        if (!vr.result) {
            tbxEmail.setText("");
            tbxEmail.requestFocus();
            return vr;
        }
        
        vr.result = true;
        vr.message = "PASSED";
        return vr;
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainInfo = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                g.drawImage(new Settings().BACKGROUND_IMAGE_BODY, 0, 0, getWidth(), getHeight(), this);
            }
        };
        btnAddUser = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tbxComfirmPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbxPhone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tbxUsername = new javax.swing.JTextField();
        tbxEmail = new javax.swing.JTextField();
        tbxPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbUserLevel = new javax.swing.JComboBox<>();
        pnlHeader = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                g.drawImage(new Settings().BACKGROUND_IMAGE_HEADER, 0, 0, getWidth(), getHeight(), this);
            }
        };
        lblTitle = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setOpaque(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        pnlMainInfo.setBackground(new java.awt.Color(102, 102, 102));
        pnlMainInfo.setForeground(new java.awt.Color(204, 204, 204));

        btnAddUser.setBackground(new java.awt.Color(0, 153, 204));
        btnAddUser.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnAddUser.setText("Add");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 204, 0));
        btnCancel.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 2, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Confirm Password: ");
        jLabel5.setToolTipText("");

        tbxComfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbxComfirmPassword.setMaximumSize(new java.awt.Dimension(1000, 25));
        tbxComfirmPassword.setMinimumSize(new java.awt.Dimension(100, 25));
        tbxComfirmPassword.setPreferredSize(new java.awt.Dimension(7, 25));
        tbxComfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbxComfirmPasswordFocusGained(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 2, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Phone: ");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 2, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Username: ");
        jLabel2.setPreferredSize(new java.awt.Dimension(45, 20));

        tbxPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbxPhone.setMaximumSize(new java.awt.Dimension(1000, 25));
        tbxPhone.setMinimumSize(new java.awt.Dimension(100, 25));
        tbxPhone.setPreferredSize(new java.awt.Dimension(7, 25));
        tbxPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbxPhoneFocusGained(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 2, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Password: ");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 2, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText(" Email: ");

        tbxUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbxUsername.setMaximumSize(new java.awt.Dimension(1000, 25));
        tbxUsername.setMinimumSize(new java.awt.Dimension(100, 25));
        tbxUsername.setPreferredSize(new java.awt.Dimension(7, 25));
        tbxUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbxUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbxUsernameFocusLost(evt);
            }
        });

        tbxEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbxEmail.setMaximumSize(new java.awt.Dimension(1000, 25));
        tbxEmail.setMinimumSize(new java.awt.Dimension(100, 25));
        tbxEmail.setPreferredSize(new java.awt.Dimension(7, 25));
        tbxEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbxEmailFocusGained(evt);
            }
        });

        tbxPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbxPassword.setMaximumSize(new java.awt.Dimension(1000, 25));
        tbxPassword.setMinimumSize(new java.awt.Dimension(100, 25));
        tbxPassword.setPreferredSize(new java.awt.Dimension(7, 25));
        tbxPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbxPasswordFocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("4-16 Characters [A-Z, a-z]");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("4-16 Characters [A-Z, a-z, 0-9, Symbols]");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 2, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("User Level: ");

        cmbUserLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Supervisor", "Manager" }));
        cmbUserLevel.setMaximumSize(new java.awt.Dimension(200, 25));
        cmbUserLevel.setMinimumSize(new java.awt.Dimension(57, 25));
        cmbUserLevel.setPreferredSize(new java.awt.Dimension(57, 25));

        pnlHeader.setBackground(new java.awt.Color(0, 102, 153));

        lblTitle.setBackground(new java.awt.Color(51, 51, 51));
        lblTitle.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("NEW USER");

        lblIcon.setForeground(new java.awt.Color(204, 204, 204));
        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user64.png"))); // NOI18N
        lblIcon.setPreferredSize(new java.awt.Dimension(68, 68));

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainInfoLayout = new javax.swing.GroupLayout(pnlMainInfo);
        pnlMainInfo.setLayout(pnlMainInfoLayout);
        pnlMainInfoLayout.setHorizontalGroup(
            pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainInfoLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainInfoLayout.createSequentialGroup()
                        .addGroup(pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainInfoLayout.createSequentialGroup()
                                .addComponent(btnAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tbxUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbxComfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbxEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbxPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbUserLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(43, 43, 43))
            .addComponent(pnlHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainInfoLayout.setVerticalGroup(
            pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainInfoLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxComfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cmbUserLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlMainInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        
        setFrameState(frameState.INIT);
        this.hide();
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
                       
        String password1 = tbxPassword.getText().trim();
        String password2 = tbxComfirmPassword.getText().trim();
        if (!password1.equals(password2)) {
            JOptionPane.showMessageDialog(this, "Password does not match.","VALIDATION WARNING",JOptionPane.WARNING_MESSAGE);
            tbxPassword.setText("");
            tbxComfirmPassword.setText("");
            tbxPassword.requestFocus();
            return;
        }
        
        User.UserInfo ui = new User.UserInfo();
        ui.id = 0;
        ui.username = tbxUsername.getText().trim();
        ui.password = tbxPassword.getText().trim();
        ui.email = tbxEmail.getText().trim();
        ui.phone = tbxPhone.getText().trim();
        ui.level = (cmbUserLevel.getSelectedIndex()*30) + 1;
        
        ValidationResult vr = validateUser(ui);
        
        if (vr.result) {
            // Encrypt password
            ui.password = encrypt(ui.password, SECRET_KEY);   
            
            User newUser = User.addUser(ui);
            if(newUser != null){
                Log.LogInfo li = new Log.LogInfo();
                li.id = 0;
                li.log_date = getCurrentDateTimeFormatted();
                li.user = CURRENT_USER.username;
                li.category = "SYSTEM LOG";
                li.event = "ADD USER";            
                li.details = "User '"+CURRENT_USER.username+"' (User Level: "+getUserLevel(CURRENT_USER.level)+") \n"
                        + "ADD NEW USER\n"
                        + " User[\n"
                        + "  ID: "+newUser.getId()+",\n"
                        + "  Username: "+newUser.getUsername()+",\n"
                        + "  Password: <***SECRET***>,\n"
                        + "  Email: "+newUser.getEmail()+",\n"
                        + "  Phone: "+newUser.getPhone()+",\n"
                        + "  UserLevel: "+getUserLevel(newUser.getLevel())+",\n"
                        + "  Result: SUCCESS\n"
                        + " ]";
                Log.addLog(li);
                
                JOptionPane.showMessageDialog(this, "Add new User successful.","SUCCESSFUL.",JOptionPane.INFORMATION_MESSAGE);                
                setFrameState(frameState.POST_EDIT);                
                tbxUsername.requestFocus();
            }else{
                JOptionPane.showMessageDialog(this, "Add new User failed.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, vr.message, "VALIDATION WARNING", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void tbxUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbxUsernameFocusLost
        
        String username = tbxUsername.getText().trim();
        if (username.length() >= 4) {
            User user = User.isExist("username='"+username+"'");
            if(user != null) {
                JOptionPane.showMessageDialog(this, "Username '"+user.getUsername()+"' is already exists.", "Error", JOptionPane.ERROR_MESSAGE);
                tbxUsername.setText("");
                tbxUsername.requestFocus();
            }            
        }
        
    }//GEN-LAST:event_tbxUsernameFocusLost

    private void tbxUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbxUsernameFocusGained
        tbxUsername.selectAll();
    }//GEN-LAST:event_tbxUsernameFocusGained

    private void tbxPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbxPasswordFocusGained
        tbxPassword.selectAll();
    }//GEN-LAST:event_tbxPasswordFocusGained

    private void tbxComfirmPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbxComfirmPasswordFocusGained
        tbxComfirmPassword.selectAll();
    }//GEN-LAST:event_tbxComfirmPasswordFocusGained

    private void tbxEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbxEmailFocusGained
        tbxEmail.selectAll();
    }//GEN-LAST:event_tbxEmailFocusGained

    private void tbxPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbxPhoneFocusGained
        tbxPhone.selectAll();
    }//GEN-LAST:event_tbxPhoneFocusGained

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
        setFrameState(frameState.INIT);
        
    }//GEN-LAST:event_formComponentShown

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        
        if (Varibles.CURRENT_USER.level < 90 && cmbUserLevel.getItemCount() == 3) {
            cmbUserLevel.removeItemAt(2);
        }
        
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cmbUserLevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMainInfo;
    private javax.swing.JPasswordField tbxComfirmPassword;
    private javax.swing.JTextField tbxEmail;
    private javax.swing.JPasswordField tbxPassword;
    private javax.swing.JTextField tbxPhone;
    private javax.swing.JTextField tbxUsername;
    // End of variables declaration//GEN-END:variables
}
