/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import DBCLS.Log;
import static GLOBAL.HelperFunctions.*;
import GLOBAL.Settings;
import static GLOBAL.Settings.BG_DARK;
import static GLOBAL.Settings.MAIN_FONT;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Graphics;
import javax.swing.event.ListSelectionEvent;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author feinz
 */
public class SystemLogViewerForm extends javax.swing.JInternalFrame {

    DefaultTableModel modelLogList = new DefaultTableModel();
    
    /**
     * Creates new form SystemLogViewerForm
     */
    public SystemLogViewerForm() {
        initComponents();
        setUIFont(new FontUIResource(MAIN_FONT));
        getContentPane().setBackground(BG_DARK);
        
        modelLogList = (DefaultTableModel)tblLogList.getModel();
        
        jdcReportStart.setDate(getCurrentDate());
        jdcReportEnd.setDate(getCurrentDate());
        JTextFieldDateEditor editor;
        editor = (JTextFieldDateEditor) jdcReportStart.getDateEditor();
        editor.setEditable(false);
        editor = (JTextFieldDateEditor) jdcReportEnd.getDateEditor();
        editor.setEditable(false);
        tbxContent.setEditable(false);
        
        tblLogList.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            int curRow = tblLogList.getSelectedRow();
            int logID;
            Log log;
            if (curRow > -1) {
                logID = Integer.parseInt(tblLogList.getValueAt(curRow, 3).toString());
                log = new Log(logID);
                tbxContent.setText(log.getDetails());
                tbxContent.setSelectionStart(0);
                tbxContent.setSelectionEnd(0);
            }            
        });
        
    }
    
    /*==== Required Code Structure ====*/
    public void callFunction(String functionName) {
        switch(functionName) {
            case "initForm" -> initForm();
        }
    }
    
    enum frameState {
        INIT, FILTERED, SELECTED
    }
    
    private void initForm() {
        setFrameState(frameState.INIT);
    }
    
    private void setFrameState(frameState framState) {
        switch(framState) {
            case INIT -> {
                jdcReportStart.setDate(getCurrentDate());
                jdcReportEnd.setDate(getCurrentDate());
                cmbLogType.setSelectedIndex(0);
                tbxFilter.setText("");
                resetContent();
            }
            
            case FILTERED -> {
                
            }
            
            case SELECTED -> {
                
            }
        }
    }
    
    /*==== Helper Functions ====*/
    
    private void resetContent() {
        
        tbxFilter.setText("");
        modelLogList.setRowCount(0);
        tbxContent.setText("");
        
    }
    
    /*==== Required Functions ====*/
    
    private void listLogs() {
        
        String dateStart = getDateFormatted(jdcReportStart.getDate());
        String dateEnd = getDateFormatted(jdcReportEnd.getDate());
        String category = String.valueOf(cmbLogType.getSelectedItem().toString());
        String filter = tbxFilter.getText().trim();
        String cond = ""
                + "log_date between '"+dateStart+" 00:00:00' and '"+dateEnd+" 23:59:59'"
                + " and category = '"+category+"'"
                + " and details like '%"+filter+"%'";
        System.out.println("Cond: "+cond);
        int row = 0;
        modelLogList.setRowCount(0);
        for (Log log: Log.listLog(cond, "log_date desc")) {
            modelLogList.addRow(new Object[0]);
            modelLogList.setValueAt(log.getLog_date(), row, 0);
            modelLogList.setValueAt(log.getUser(), row, 1);
            modelLogList.setValueAt(log.getEvent(), row, 2);
            modelLogList.setValueAt(log.getId(), row, 3);
            row++;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBody = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                g.drawImage(new Settings().BACKGROUND_IMAGE_BODY, 0, 0, getWidth(), getHeight(), this);
            }
        };
        pnlHeader = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                g.drawImage(new Settings().BACKGROUND_IMAGE_HEADER, 0, 0, getWidth(), getHeight(), this);
            }
        };
        lblTitle = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        pnlFilter = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g){
                g.drawImage(new Settings().BACKGROUND_IMAGE_BODY_PORTRAIT, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jdcReportEnd = new com.toedter.calendar.JDateChooser();
        btnReport = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbLogType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jdcReportStart = new com.toedter.calendar.JDateChooser();
        tbxFilter = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLogList = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbxContent = new javax.swing.JTextArea();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setResizable(true);
        setMaximumSize(new java.awt.Dimension(1200, 1900));
        setMinimumSize(new java.awt.Dimension(1200, 950));
        setPreferredSize(new java.awt.Dimension(1200, 950));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pnlHeader.setBackground(new java.awt.Color(0, 102, 153));

        lblTitle.setBackground(new java.awt.Color(51, 51, 51));
        lblTitle.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("LOG VIEWER");

        lblIcon.setForeground(new java.awt.Color(204, 204, 204));
        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logs64.png"))); // NOI18N
        lblIcon.setPreferredSize(new java.awt.Dimension(68, 68));

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFilter.setBackground(new java.awt.Color(153, 51, 0));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("To");

        jdcReportEnd.setBackground(new java.awt.Color(153, 51, 0));
        jdcReportEnd.setDateFormatString("yyyy-MM-dd");
        jdcReportEnd.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jdcReportEnd.setOpaque(false);
        jdcReportEnd.setPreferredSize(new java.awt.Dimension(88, 29));
        jdcReportEnd.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdcReportEndPropertyChange(evt);
            }
        });

        btnReport.setBackground(new java.awt.Color(153, 204, 255));
        btnReport.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/view-logs.png"))); // NOI18N
        btnReport.setText("View Logs");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("From");

        cmbLogType.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        cmbLogType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "System Log", "Application Log" }));
        cmbLogType.setPreferredSize(new java.awt.Dimension(57, 29));
        cmbLogType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLogTypeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Type");

        jdcReportStart.setBackground(new java.awt.Color(153, 51, 0));
        jdcReportStart.setDateFormatString("yyyy-MM-dd");
        jdcReportStart.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jdcReportStart.setOpaque(false);
        jdcReportStart.setPreferredSize(new java.awt.Dimension(88, 29));
        jdcReportStart.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdcReportStartPropertyChange(evt);
            }
        });

        tbxFilter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbxFilter.setMaximumSize(new java.awt.Dimension(2147483647, 27));
        tbxFilter.setMinimumSize(new java.awt.Dimension(7, 27));
        tbxFilter.setPreferredSize(new java.awt.Dimension(60, 29));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Filter");

        javax.swing.GroupLayout pnlFilterLayout = new javax.swing.GroupLayout(pnlFilter);
        pnlFilter.setLayout(pnlFilterLayout);
        pnlFilterLayout.setHorizontalGroup(
            pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilterLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReport)
                    .addGroup(pnlFilterLayout.createSequentialGroup()
                        .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbxFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdcReportEnd, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(jdcReportStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbLogType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnlFilterLayout.setVerticalGroup(
            pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilterLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcReportStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdcReportEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbLogType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        tblLogList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblLogList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Account", "Event", "RealID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLogList.setRowHeight(24);
        tblLogList.setShowVerticalLines(false);
        tblLogList.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblLogList);
        if (tblLogList.getColumnModel().getColumnCount() > 0) {
            tblLogList.getColumnModel().getColumn(0).setMinWidth(200);
            tblLogList.getColumnModel().getColumn(0).setPreferredWidth(200);
            tblLogList.getColumnModel().getColumn(0).setMaxWidth(200);
            tblLogList.getColumnModel().getColumn(1).setMinWidth(150);
            tblLogList.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblLogList.getColumnModel().getColumn(1).setMaxWidth(150);
            tblLogList.getColumnModel().getColumn(3).setMinWidth(0);
            tblLogList.getColumnModel().getColumn(3).setPreferredWidth(0);
            tblLogList.getColumnModel().getColumn(3).setMaxWidth(0);
        }

        tbxContent.setBackground(new java.awt.Color(240, 240, 240));
        tbxContent.setColumns(20);
        tbxContent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbxContent.setRows(5);
        jScrollPane1.setViewportView(tbxContent);

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(pnlFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed

        listLogs();
        
    }//GEN-LAST:event_btnReportActionPerformed

    private void cmbLogTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLogTypeActionPerformed
        
        resetContent();
        
    }//GEN-LAST:event_cmbLogTypeActionPerformed

    private void jdcReportStartPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdcReportStartPropertyChange
        
        resetContent();
        
    }//GEN-LAST:event_jdcReportStartPropertyChange

    private void jdcReportEndPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdcReportEndPropertyChange
        
        resetContent();
        
    }//GEN-LAST:event_jdcReportEndPropertyChange

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        
        setFrameState(frameState.INIT);
        
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReport;
    private javax.swing.JComboBox<String> cmbLogType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jdcReportEnd;
    private com.toedter.calendar.JDateChooser jdcReportStart;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlFilter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JTable tblLogList;
    private javax.swing.JTextArea tbxContent;
    private javax.swing.JTextField tbxFilter;
    // End of variables declaration//GEN-END:variables
}
